### ISSUE TITLE
Pets count as poorly scaled players in instances.

### ISSUE THREAD

**Issue by TenebrisWoW** [azerothcore/mod-solocraft#28]
Hunter and Warlock pets are counted as players when entering an instance, but scale so badly that they die quickly and do such bad damage that even tank pets do not hold aggro. This makes the corresponding classes in the solo content unusable.

**Comment by entropiccode** [comment]
I've been playing a hunter through dungeons utilizing SoloCraft, and there are definitely a number of issues with pets.

Pets health gets scaled, which is helpful.  However, as mentioned above their damage does not seem to scale.  Additionally, there are no modifications made to their threat generating abilities, so player characters are very quickly able to peel off of their pets, even when built to emphasize pet damage/aggro generation.

Furthermore, the increased health makes it frustrating to heal the pets, as the available spells to do so heal at a fixed rate.  It takes a while to heal my pet bear with 20k hp when mend pet ticks for 400 health.

Scaling pet damage up alongside player damage would end up making pet classes too powerful, so simply increasing pet damage isn't the solution here.  

Instead, I think it would be prudent to automatically transfer some of the player generated threat via damage to the pet (assuming Hunter pet or Warlock Voidwalker/Felguard).  Alternatively, make player threat also generate the same amount of pet threat, but only if the pet has aggro on that target (this would keep Misdirect useful as a tool to boost pet threat during a pull, or pulling a non-engaged creature over to the pet).
Pet armor values should also be scaled up, as I often found I was better able to tank a pack of dungeon enemies better more effectively than my pet.
Lastly, pets should receive a boost to out of combat health regeneration, so that a pet could heal to full over the course of 20 seconds or so (the same amount of time it would take to sit down and eat).

**Comment by pangolp** [comment]
Good afternoon, currently I don't know if you are still using the emulator and the module, but for now, to try to clean up the repository and receive current reports, I'm going to close this topic. In case, that you are still using the module, and the error that you describe, still occurs, I ask you to open a problem again and we try to find a solution to the problem, in case they really start. Thank you.
