### ISSUE TITLE
wont compile forme

### ISSUE THREAD

**Issue by godlike73** [azerothcore/mod-solocraft#39]
wont compile for me get this error
/usr/src/azerothcore/modules/mod-solocraft/src/Solocraft.cpp:343:90: fatal error: non-virtual member function marked 'override' hides virtual member function
        void OnGiveXP(Player* /*player*/, uint32& amount, Unit* /*victim*/, uint8 /*xpSource*/) override

**Comment by Druark** [comment]
Are you using the most up-to-date version of AzerothCore? 

As of right now that's this commit: [](https://github.com/azerothcore/azerothcore-wotlk/commit/79b304cf082a20aaed63f7acd3e347d7ed1c946e)

I had errors trying to compile too until I updated my server to a more recent version. Now using the commit above it compiles OK.

**Comment by pangolp** [comment]
Technically this issue is not valid. I have not compiled with the latest version of AzerothCore, and I have not had any problems. So I think the problem comes with respect to updating the emulator. The module as well as the emulator, are continuously receiving improvements, so it is necessary to update both, to continue using them.
